- name: Send Report via E-mail
  community.general.mail:
    host: "{{ EMAIL_HOST }}"
    username: "{{ EMAIL_USERNAME }}"
    password: "{{ EMAIL_PASSWORD }}"
    port: "{{ EMAIL_PORT }}"
    subject: "Linux Patching Report"
    body: "{{ lookup('template', 'report.j2') }}"
    from: "{{ email_from }}"
    to: "{{ email_to }}"
    subtype: html
  delegate_to: localhost
  become: false
  check_mode: false
  when: sendemailreport
