---
- name: Find rescue kernel files
  ansible.builtin.find:
    paths: /boot
    patterns: "vmlinuz-0-rescue-*"
    file_type: file
  register: rescue_kernels

- name: Sort rescue kernels by modification time (newest first)
  ansible.builtin.set_fact:
    sorted_rescue_kernels: "{{ rescue_kernels.files | sort(attribute='mtime', reverse=True) }}"

- name: Keep 2 most recent rescue kernels, remove older ones
  ansible.builtin.set_fact:
    old_rescue_kernels: "{{ sorted_rescue_kernels[2:] | map(attribute='path') | list }}"
  when: sorted_rescue_kernels | length > 2

- name: Build list of files to remove (kernel, initramfs, loader entry)
  ansible.builtin.set_fact:
    files_to_remove: >-
      {{
        old_rescue_kernels
        | map('basename')
        | map('regex_replace', '^vmlinuz-0-rescue-(.*)$', '\1')
        | map('regex_replace', '^(.*)$', '/boot/vmlinuz-0-rescue-\1')
        + old_rescue_kernels
        | map('basename')
        | map('regex_replace', '^vmlinuz-0-rescue-(.*)$', '\1')
        | map('regex_replace', '^(.*)$', '/boot/initramfs-0-rescue-\1.img')
        + old_rescue_kernels
        | map('basename')
        | map('regex_replace', '^vmlinuz-0-rescue-(.*)$', '\1')
        | map('regex_replace', '^(.*)$', '/boot/loader/entries/\1.conf')
      }}
  when: old_rescue_kernels is defined

- name: Remove old rescue kernel, initramfs, and loader entries
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove | default([]) }}"
  register: removed_files
  when: files_to_remove is defined

- name: Print removed files
  ansible.builtin.debug:
    msg: "{{ removed_files.results | selectattr('changed','equalto',true) | map(attribute='item') | list }}"
  when: removed_files is defined
