---
- name: Send prepatching email
  hosts: all
  gather_facts: true
  vars_files: ../group_vars/email-creds.yml

  tasks:
    - name: Send Notification via E-mail
      community.general.mail:
        host: "{{ EMAIL_HOST }}"
        username: "{{ EMAIL_USERNAME }}"
        password: "{{ EMAIL_PASSWORD }}"
        port: "{{ EMAIL_PORT }}"
        subject: "Linux OS Patching Life Cycle - {{ SERVICE }} - {{ ENV }}"
        body: "{{ lookup('template', 'templates/one_hour_notification.j2') }}"
        from: "{{ email_from }}"
        to: "{{ email_to }}"
        subtype: html
      delegate_to: localhost
      become: false
      check_mode: false
      run_once: true
  #when: sendemailreport

