---
- name: Start the web service
  hosts: all
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml

  tasks:

    - name: Start the web service {{ WEB_SERVICE }}
      ansible.builtin.systemd:
        name: "{{ WEB_SERVICE }}"
        state: started
      become: true
      register: startweb-result
      tags: startweb

    - name: Confirm web service is UP
      ansible.builtin.uri:
      url: "http://{{ WEB_URL }}:{{ WEB_PORT }}"
        method: GET
        status_code: 200
        return_content: no
        validate_certs: no
        retries: 3
      delay: 10
      register: web_health_check
      until: web_health_check.status == 200  

    - name: Web service access result
      ansible.builtin.debug:
        msg: "Started service: {{ WEB_SERVICE }}"
      when: web_health_check.status == 200
      tags: startweb-result-msg
